apiVersion: v1
kind: Secret
metadata:
  name: credentials
data:
  USERNAME: YXdpcw== #awis
  PASSWORD: cGFzc3dvcmQ= #password


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest
        env:
        - name: CONTENT
          valueFrom:
            configMapKeyRef:
              name: q5
              key: content
        - name: USERNAME
          valueFrom:
           secretKeyRef:
             name: credentials
             key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: PASSWORD
        ports:
        - containerPort: 80
